apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: ebikeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: fabionotaro2/apigateway:latest
          ports:
            - containerPort: 10000
          env:
            - name: REGISTRY_URL
              value: "http://registry:9000"
            - name: USERS_URL
              value: "http://users:9100"
            - name: EBIKES_URL
              value: "http://ebikes:9200"
            - name: APIGATEWAY_URL
              value: "http://apigateway:10000"
            - name: RIDES_URL
              value: "http://rides:9300"
            - name: KAFKA_BROKER_URL
              value: "kafka:9092"
