apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: ebikeapp
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
  type: ClusterIP
