apiVersion: v1
kind: ConfigMap
metadata:
  name: ebikeapp-config
  namespace: ebikeapp
data:
  REGISTRY_URL: "http://registry:9000"
  USERS_URL: "http://users:9100"
  EBIKES_URL: "http://ebikes:9200"
  APIGATEWAY_URL: "http://apigateway:10000"
  RIDES_URL: "http://rides:9300"
  KAFKA_BROKER_URL: "kafka:9092"
