apiVersion: v1
kind: Service
metadata:
  name: ebikes
  namespace: ebikeapp
spec:
  selector:
    app: ebikes
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
