apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebikes
  namespace: ebikeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebikes
  template:
    metadata:
      labels:
        app: ebikes
    spec:
      containers:
        - name: ebikes
          image: fabionotaro2/ebikes:latest
          ports:
            - containerPort: 9200
          env:
            - name: REGISTRY_URL
              value: "http://registry:9000"
            - name: EBIKES_URL
              value: "http://ebikes:9200"
            - name: KAFKA_BROKER_URL
              value: "kafka:9092"