apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: ebikeapp  # Usa il namespace creato
spec:
  replicas: 1  # Numero di istanze del servizio
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:latest  # Nome immagine
          ports:
            - containerPort: 9000  # Porta interna del container
          env:
            - name: REGISTRY_URL
              value: "http://registry:9000"  # Variabile d'ambiente
            - name: KAFKA_BROKER_URL
              value: "kafka:9092"  # Variabile d'ambiente