apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: ebikeapp
spec:
  selector:
    app: registry  # Collegamento al Deployment
  ports:
    - protocol: TCP
      port: 9000  # Porta esterna del servizio
      targetPort: 9000  # Porta interna del container
  type: ClusterIP  # Rende il servizio accessibile solo nella rete cluster
