apiVersion: apps/v1
kind: Deployment
metadata:
  name: rides
  namespace: ebikeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rides
  template:
    metadata:
      labels:
        app: rides
    spec:
      containers:
        - name: rides
          image: fabionotaro2/rides:latest
          ports:
            - containerPort: 9300
          env:
            - name: REGISTRY_URL
              value: "http://registry:9000"
            - name: USERS_URL
              value: "http://users:9100"
            - name: EBIKES_URL
              value: "http://ebikes:9200"
            - name: RIDES_URL
              value: "http://rides:9300"
            - name: KAFKA_BROKER_URL
              value: "kafka:9092"
          command: ["/bin/sh", "-c"]
          args: [
            "sleep 30 && mvn clean install && mvn exec:java -Dexec.mainClass=sap.ass2.rides.RidesManagerLauncher"
          ]
