apiVersion: v1
kind: Service
metadata:
  name: rides
  namespace: ebikeapp
spec:
  selector:
    app: rides
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300
  type: ClusterIP
