apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: ebikeapp  # Aggiungi il namespace (se esiste)
spec:
  replicas: 1  # Numero di istanze
  selector:
    matchLabels:
      app: users  # Etichetta usata per collegare Service e Deployment
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: fabionotaro2/users:latest  # L'immagine del container
          ports:
            - containerPort: 9100  # Porta esposta dal container
          env:  # Variabili d'ambiente
            - name: REGISTRY_URL
              value: "http://registry:9000"
            - name: USERS_URL
              value: "http://users:9100"
            - name: KAFKA_BROKER_URL
              value: "kafka:9092"
