apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: ebikeapp
spec:
  selector:
    app: users  # Collegamento al Deployment
  ports:
    - protocol: TCP
      port: 9100  # Porta visibile sulla rete del cluster
      targetPort: 9100  # Porta interna del container
  type: ClusterIP  # Accessibile solo nella rete del cluster
